# Generated by Django 5.1.4 on 2025-01-02 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEPDatosPercepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('fecha', models.DateField()),
                ('encuesta', models.IntegerField()),
                ('detalle_encuesta', models.CharField(max_length=255)),
                ('grupo', models.CharField(max_length=50)),
                ('variable', models.CharField(max_length=255)),
                ('porcentaje', models.FloatField()),
                ('porcentaje_ic_inferior', models.FloatField()),
                ('porcentaje_ic_superior', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CorruptionPerceptionIndexChile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('pais', models.CharField(max_length=100)),
                ('cpi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinciaChileCUT',
            fields=[
                ('cut_provincia', models.IntegerField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegionChileCUT',
            fields=[
                ('cut_region', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ComunaChileCUT',
            fields=[
                ('cut_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=255)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.provinciachilecut')),
            ],
        ),
        migrations.AddField(
            model_name='provinciachilecut',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.regionchilecut'),
        ),
        migrations.CreateModel(
            name='CasoCorrupcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caso', models.CharField(max_length=255)),
                ('monto', models.BigIntegerField(blank=True, null=True)),
                ('año', models.IntegerField()),
                ('año_inicio', models.IntegerField(blank=True, null=True)),
                ('año_fin', models.IntegerField(blank=True, null=True)),
                ('comuna', models.CharField(blank=True, max_length=255, null=True)),
                ('posicion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('sentencia', models.CharField(blank=True, max_length=255, null=True)),
                ('condena', models.CharField(blank=True, max_length=255, null=True)),
                ('conclusiones', models.TextField(blank=True, null=True)),
                ('partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.partido')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.responsable')),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.sector'),
        ),
    ]
