# Generated by Django 5.1.4 on 2025-01-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casocorrupcion',
            old_name='año_fin',
            new_name='ano_fin',
        ),
        migrations.RenameField(
            model_name='casocorrupcion',
            old_name='año_inicio',
            new_name='ano_inicio',
        ),
    ]
