# Generated by Django 5.1.4 on 2025-01-02 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_año_fin_casocorrupcion_ano_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Resuelto', 'Resuelto'), ('En Proceso', 'En Proceso'), ('Cerrado', 'Cerrado')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='casocorrupcion',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.comunachilecut'),
        ),
        migrations.AlterField(
            model_name='casocorrupcion',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.estado'),
        ),
    ]
