# Generated by Django 5.1.4 on 2025-01-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_estado_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casocorrupcion',
            name='responsable',
        ),
        migrations.AddField(
            model_name='casocorrupcion',
            name='responsables',
            field=models.ManyToManyField(blank=True, to='data.responsable'),
        ),
    ]
