# Generated by Django 5.1.4 on 2025-01-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_partido_color_sector_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casocorrupcion',
            name='estado',
            field=models.CharField(choices=[('En Proceso', 'En Proceso'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado'), ('En Investigación', 'En Investigación'), ('Formalizado', 'Formalizado'), ('Sentenciado', 'Sentenciado'), ('Condenado', 'Condenado')], default='En Proceso', max_length=255),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
