# Generated by Django 5.1.4 on 2025-01-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_casocorrupcion_estado_delete_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='fecha_fundacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='partidos/'),
        ),
        migrations.AddField(
            model_name='partido',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
