# Generated by Django 4.2.17 on 2025-01-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_partido_descripcion_partido_fecha_fundacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casocorrupcion',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='casocorrupcion',
            name='partido',
        ),
        migrations.AddField(
            model_name='casocorrupcion',
            name='comuna',
            field=models.ManyToManyField(blank=True, to='data.comunachilecut'),
        ),
        migrations.AddField(
            model_name='casocorrupcion',
            name='partido',
            field=models.ManyToManyField(blank=True, to='data.partido'),
        ),
    ]
