# Generated by Django 4.2.17 on 2025-01-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_casocorrupcion_comuna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparacionMonetaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('valor', models.BigIntegerField(help_text='Valor en pesos chilenos')),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='comparaciones/')),
            ],
            options={
                'verbose_name': 'Comparación Monetaria',
                'verbose_name_plural': 'Comparaciones Monetarias',
            },
        ),
    ]
