# Generated by Django 4.2.17 on 2025-01-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_comparacionmonetaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='casocorrupcion',
            name='comparaciones',
            field=models.ManyToManyField(blank=True, related_name='casos', to='data.comparacionmonetaria'),
        ),
    ]
